config/routes.rb
Waiter::Application.routes.draw do

  get "home/index"
  post "home/record"

  devise_for :users

  root :to => "home#index"

  resources :biometrics do
    collection do
      get :all
      get :weight
      get :heartrate
      get :systolic
      get :diastolic
    end
  end

  resources :events do
    collection do
      get :all
      get :search
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?

      @biometrics = Biometric.where(:user_id => current_user.id).order('record_date asc')

      @biometric = current_user.biometrics.build()

      @events =  Event.where(:user_id => current_user.id).order('event_date desc')
      @event = current_user.events.build()
    else

      render :template => "home/logged_out"

    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_data_entry_tab.html.erb
<% last_14 = @biometrics.reverse[0..13] %>
<script>

  function addBiometric(biometric) {

    $('#biometric_form_row').after("<tr><td>" + formatDate(biometric["record_date"]) +
         "</td><td>" + blankIfNull(biometric["weight"]) +
         "</td><td>" + blankIfNull(biometric["systolic"]) +
         "</td><td>" + blankIfNull(biometric["diastolic"]) +
         "</td><td>" + blankIfNull(biometric["bpm"]) +
         "</td><td><a href='/biometrics/" + biometric["id"] + "'>edit</a>" +

         "</td></tr>");
  }

  function clearBiometricForm() {
    $('#biometric_weight').val('');
    $('#biometric_systolic').val('');
    $('#biometric_diastolic').val('');
    $('#biometric_bpm').val('');
  }

  $(document).ready(function() {
    $('#biometric_button').bind('click', function () { 
        $('#biometric_button').attr('disabled', true);
        $.post("/biometrics", $("#new_biometric").serialize(),function(data){
           $('#biometric_button').attr('disabled', false);
           addBiometric(data['biometric']);
           clearBiometricForm();
          }, "json");
        return false;
       });
  });

</script>
<%= form_for @biometric  do |f| %>

<table class="biometric_data">
  <tr>
    <td>Date</td>
    <td>Weight</td>
    <td>Systolic</td>
    <td>Diastolic</td>
    <td>BPM</td>
    <td></td>
  </tr>
  <tr id="biometric_form_row">
  <% if @biometric.record_date.nil? %>
    <td><%= f.text_field :record_date, :value => "now" %></td>
  <% else %>
    <td><%= f.text_field :record_date, :value => @biometric.record_date.to_date %></td>
  <% end %>
    <td><%= f.text_field :weight, :maxlength => 5 %></td>
    <td><%= f.text_field :systolic, :maxlength => 5 %></td>
    <td><%= f.text_field :diastolic, :maxlength => 5 %></td>
    <td><%= f.text_field :bpm, :maxlength => 5 %></td>
    <td><%= f.submit "Record", :id => "biometric_button" %></td>
  </tr>
<% last_14.each do |b| %>
  <% unless b.new_record? %>
  <tr>
    <td><%= pretty_date b.record_date %></td>
    <td><%= b.weight %></td>
    <td><%= b.systolic %></td>
    <td><%= b.diastolic %></td>
    <td><%= b.bpm %></td>
    <td><%= link_to "edit", b %></td>
  </tr>
  <% end %>
<% end %>
</table>
<% end %>
<p>
download as <a href="/biometrics/all.csv">CSV</a>
or <a href="/biometrics/all.xml">XML</a>.

app/views/home/_events_search_tab.html.erb
<script>

  function addSearchEvents(events) {
    console.log(events);
    for(i = 0; i < events.length; i++){
      addSearchEvent(events[i]);
    }
  }

  function addSearchEvent(event) {
    console.log("adding event");
    console.log(event);
    $('#results_table').children().last().after("<tr class=\"search_result\"><td class=\"timestamp\">" + event["display_time"] +
         "</td><td>" + blankIfNull(event["quantity"]) +
         "</td><td>" + blankIfNull(event["description"]) +
     "</td><td><a href=\"/events/" + event["id"] + "/edit\">edit</a></td></tr>");
  }

  function clearSearchResults() {
    $('.search_result').remove();
  }


  $(document).ready(function() {
    $('#event_search_button').bind('click', function () { 
        $('#event_search_button').attr('disabled', true);
        $.get("/events/search.json",
              $("#search_form").serialize(),function(data){
                clearSearchResults();
                console.log(data['events']);
                $('#event_search_button').attr('disabled', false);
                addSearchEvents(data['events']);
                $('#results_table').slideDown();
              }, "json");
        return false;
    });
  });

</script>
<form id="search_form" action="/events/search.json" method="get">
    <input type="text" name="q" />
    <input type="submit" id="event_search_button" value="Search" />
</form>
<table class="event_data" id="results_table" style="display:none">
  <tr>
    <th>Date</th>
    <th>Quantity</th>
    <th>Description</th>
  </tr>
</table>

app/views/home/_events_tab.html.erb
<% last_14 = @events[0..13] %>
<script>

  function addEvent(event) {
    $('#event_form_row').after("<tr><td>" + event["display_time"] +
         "</td><td>" + blankIfNull(event["quantity"]) +
         "</td><td>" + blankIfNull(event["description"]) +
     "</td><td><a href=\"/events/" + event["id"] + "/edit\">edit</a></td></tr>");
  }

  function clearEventForm() {
    $('#event_quantity').val('');
    $('#event_description').val('');
  }

  $(document).ready(function() {
    $('#event_button').bind('click', function () { 
        $('#event_button').attr('disabled', true);
        $.post("/events", $("#new_event").serialize(),function(data){
           $('#event_button').attr('disabled', false);
           addEvent(data['event']);
           clearEventForm();
          }, "json");
        return false;
       });
  });

</script>
<%= form_for @event  do |f| %>

<table class="event_data">
  <tr>
    <th>Date</th>
    <th>Quantity</th>
    <th>Description</th>
  </tr>
  <tr id="event_form_row">
  <% if @event.event_date.nil? %>
    <td><%= f.text_field :event_date,
                   :value => "now" %></td>
  <% else %>
    <td><%= f.text_field :event_date,
                   :value => @event.event_date.to_date %></td>
  <% end %>
    <td><%= f.text_field :quantity,
                   :maxlength => 5 %></td>
    <td><%= f.text_field :description,
                   :maxlength => 150, :size => 45 %></td>
    <td><%= f.submit "Record", :id => 'event_button' %></td>
    <td></td>
  </tr>

  <% last_14.each do |e| %>
  <% unless e.new_record? %>
  <tr>
    <td class="timestamp"><%= pretty_time e.event_date %></td>
    <td><%= e.quantity %></td>
    <td><%= e.description %></td>
    <td><%= link_to "edit", edit_event_url(e) %></td>
  </tr>
  <% end %>
  <% end %>

</table>
<% end %>
<p>
download as <a href="/events/all.csv">CSV</a>
or <a href="/events/all.xml">XML</a>.

app/views/home/_weight_graph_tab.html.erb
<div id="placeholder" style="width:600px;height:300px;"></div>
<p>
download as: <a href="/biometrics/weight.csv">CSV</a>
    or   <a href="/biometrics/weight.xml">XML</a>
<span style="float: right; margin-right: 50px;"><input name="graph_start" type="radio" value="<%= (Time.now - 90.days).to_i %>" onclick="show_weight_graph();" checked/> last 90 days  
<input name="graph_start" type="radio" value="<%= (Time.now - 365.days).to_i %>" onclick="show_weight_graph();"/> last year  
<input name="graph_start" type="radio" value="0" onclick="show_weight_graph();"/> all time
</span>
</p>
<script id="source">
    function show_weight_graph() {
        ts = $('input[name=graph_start]:radio:checked').val();

        console.log("rendering weight graph");
        $.getJSON("/biometrics/weight.json?s=" + ts, function(data) {
            $.plot($("#placeholder"), [data], {
                xaxis: {
                    mode: "time"
                }   
            });
        });
    }
</script>

app/views/home/index.html.erb
<script type="text/javascript">
    $(function() {
          $("#tabs").tabs();
          $("#tabs").bind('tabsshow', function(event, ui) {
               if (ui.index == 1) {
                  show_weight_graph();
                }
          });
   });
</script>
<div id="tabs">
    <ul>
         <li><a href="#home">home</a></li>
         <li><a href="#weight_graph">weight graph</a></li>
         <li><a href="#events">events</a></li>
         <li><a href="#events_search">events search</a></li>
   </ul>

  <div id="home">
          <%= render :partial => "home/data_entry_tab" %>
   </div>
   <div id="weight_graph">
          <%= render :partial => "home/weight_graph_tab" %>
   </div>
   <div id="events">
          <%= render :partial => "home/events_tab" %>
   </div>
   <div id="events_search">
          <%= render :partial => "home/events_search_tab" %>
   </div>
</div>

app/views/home/logged_out.html.erb
<h2>Welcome!</h2>
<p>Waiter is a simple app for recording you biometric information.
You can record your weight, blood pressure and heart rate.
You can view graphs of how they've changed over time, and since it's
YOUR data you can always download it for use with some other application.
</p>
<p>
In order to use Waiter, you need to <%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>.
</p>