config/routes.rb
Waiter::Application.routes.draw do

  get "home/index"
  post "home/record"

  devise_for :users

  root :to => "home#index"

  resources :biometrics do
    collection do
      get :all
      get :weight
      get :heartrate
      get :systolic
      get :diastolic
    end
  end

  resources :events do
    collection do
      get :all
      get :search
    end
  end

end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
  belongs_to :user
  
  validates_numericality_of :user_id, :allow_nil => false
  validates_numericality_of :weight, :allow_nil => true
  validates_numericality_of :systolic, :allow_nil => true
  validates_numericality_of :diastolic, :allow_nil => true

  validates_numericality_of :bpm, :allow_nil => true

  validates_with BiometricValidator
end

app/controllers/biometrics_controller.rb
class BiometricsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :handle_now, :only => [ :create, :update]

  # GET /biometrics
  # GET /biometrics.xml
  def index
    @biometrics = current_user.biometrics

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @biometrics }
    end
  end

  # GET /biometrics/all.json
  # GET /biometrics/all.csv
  def all
    @biometrics = Biometric.select("systolic, diastolic, bpm, weight, record_date").where(:user_id => current_user.id).order(:record_date)

    respond_to do |format|
      format.xml  { render :xml => @biometrics }
      format.csv  { 
        csv = @biometrics.collect { |b| [b.record_date.utc.strftime("%Y/%m/%d %H:%M:%S"), b.weight, b.systolic, b.diastolic, b.bpm].to_csv }
        csv.unshift ["record date","weight","systolic","diastolic","bpm"].to_csv

        render :content_type => 'text/csv', :text =>  csv.join("")
      }
    end
  end


  # GET /biometrics/weight.json
  # GET /biometrics/weight.csv
  def weight
    t = Biometric.arel_table
    query = t[:user_id].eq(current_user.id)
    if params[:s]
      query = query.and(t[:record_date].gt(Time.at(params[:s].to_i)))
    end

    if params[:e]
      query = query.and(t[:record_date].lt(Time.at(params[:e].to_i)))
    end

    @biometrics = Biometric.select("weight, record_date").where(query).order(:record_date)

    respond_to do |format|
      format.json { render :json => @biometrics.collect { |b| [b.record_date.to_i * 1000, b.weight] } }
      format.xml  { render :xml => @biometrics }
      format.csv  { 
        csv = @biometrics.collect { |b| [b.record_date, b.weight].to_csv }
        render :content_type => 'text/csv', :text => csv.join("")
      }
    end
  end


  # GET /biometrics/1
  # GET /biometrics/1.xml
  def show
    Rails.logger.debug("current_user.id = #{current_user.id}")
    @biometric = Biometric.where(:user_id => current_user.id,
                                 :id => params[:id]).first

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @biometric }
      format.json  { render :json => @biometric }
    end
  end

  # GET /biometrics/new
  # GET /biometrics/new.xml
  def new
    @biometric = Biometric.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @biometric }
    end
  end

  # GET /biometrics/1/edit
  def edit

    @biometric = Biometric.where(:user_id => current_user.id,
                                 :id => params[:id]).first
  end

  # POST /biometrics
  # POST /biometrics.xml
  def create

    @biometric = current_user.biometrics.build(params[:biometric])

    respond_to do |format|
      if @biometric.save
        format.html { redirect_to(root_url, :notice => 'Biometric data was successfully recorded.') }
        format.xml  { render :xml => @biometric, :status => :created, :location => @biometric }
        format.json { render :json => @biometric, :status => :created, :location => @biometric }
      else
        format.html {
          @biometrics = Biometric.where(:user_id => current_user.id).order('record_date asc')
          @events =  Event.where(:user_id => current_user.id).order('event_date asc')
          @event = current_user.events.build()

          logger.debug(@biometric.errors.full_messages)
          flash[:alert] = @biometric.errors.full_messages
          render :template => "home/index"
        }
        format.xml  { render :xml => @biometric.errors, :status => :unprocessable_entity }
        format.json { render :json => @biometric.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /biometrics/1
  # PUT /biometrics/1.xml
  def update

    @biometric = Biometric.where(:user_id => current_user.id,
                                 :id => params[:id]).first

    params[:biometric].delete(:user_id)   # make sure they don't change this
    respond_to do |format|
      if @biometric.update_attributes(params[:biometric])
        format.html { redirect_to(@biometric, :notice => 'Biometric was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @biometric.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /biometrics/1
  # DELETE /biometrics/1.xml
  def destroy
    @biometric = Biometric.where(:user_id => current_user.id,
                                 :id => params[:id]).first
    @biometric.destroy

    respond_to do |format|
      format.html { redirect_to(biometrics_url) }
      format.xml  { head :ok }
    end
  end


  protected

  def handle_now
    if params[:biometric][:record_date] == "now"
      params[:biometric][:record_date] = Time.now
    end
  end

end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/views/biometrics/_form.html.erb
<%= form_for(@biometric) do |f| %>
  <% if @biometric.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@biometric.errors.count, "error") %> prohibited this biometric from being saved:</h2>
    <ul>
    <% @biometric.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :record_date %><br />
    <%= f.text_field :record_date %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :systolic %><br />
    <%= f.text_field :systolic %>
  </div>
  <div class="field">
    <%= f.label :diastolic %><br />
    <%= f.text_field :diastolic %>
  </div>
  <div class="field">
    <%= f.label :bpm %><br />
    <%= f.text_field :bpm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biometrics/edit.html.erb
<h1>Editing biometric</h1>

<%= render 'form' %>

<%= link_to 'Show', @biometric %> |
<%= link_to 'Back', root_path %>

app/views/biometrics/index.html.erb
<h1>Listing biometrics</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Weight</th>
    <th>Systolic</th>
    <th>Diastolic</th>
    <th>Bpm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @biometrics.each do |biometric| %>
  <tr>
    <td><%= biometric.record_date %></td>
    <td><%= biometric.weight %></td>
    <td><%= biometric.systolic %></td>
    <td><%= biometric.diastolic %></td>
    <td><%= biometric.bpm %></td>
    <td><%= link_to 'Show', biometric %></td>
    <td><%= link_to 'Edit', edit_biometric_path(biometric) %></td>
    <td><%= link_to 'Destroy', biometric, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Biometric', new_biometric_path %>

app/views/biometrics/new.html.erb
<h1>New biometric</h1>

<%= render 'form' %>

<%= link_to 'Back', biometrics_path %>

app/views/biometrics/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @biometric.weight %>
</p>

<p>
  <b>Systolic:</b>
  <%= @biometric.systolic %>
</p>

<p>
  <b>Diastolic:</b>
  <%= @biometric.diastolic %>
</p>

<p>
  <b>Bpm:</b>
  <%= @biometric.bpm %>
</p>

<p>
  <b>User:</b>
  <%= @biometric.user_id %>
</p>


<%= link_to 'Edit', edit_biometric_path(@biometric) %> |
<%= link_to 'Back', root_path %>